'use client'
import {useEffect,useMemo,useState} from 'react'
import {Activity,AlertTriangle,ArrowDownRight,ArrowUpRight,BarChart3,ChevronRight,Edit3,LayoutDashboard,Plus,RefreshCw,ShieldCheck,WalletCards,X} from 'lucide-react'
import type {AccountClass,TradeAccount} from '@/lib/demo'

type Tab='dashboard'|'accounts'|'risk'|'analytics'
type RiskRule={dailyLoss:number;maxLoss:number;perTrade:number}
type RiskRules=Record<string,RiskRule>
type AccountProfile={name:string;accountClass:AccountClass;stageLabel:string}
type AccountProfiles=Record<string,AccountProfile>
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)

export default function Home(){
 const [rawAccounts,setRawAccounts]=useState<TradeAccount[]>([]); const [profiles,setProfiles]=useState<AccountProfiles>({}); const [tab,setTab]=useState<Tab>('dashboard'); const [loading,setLoading]=useState(true); const [editingAccount,setEditingAccount]=useState<TradeAccount|null>(null)
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/accounts',{cache:'no-store'});const j=await r.json();setRawAccounts(j.accounts||[])}finally{setLoading(false)}}
 useEffect(()=>{load();try{const saved=localStorage.getItem('tradedeck-account-profiles');if(saved)setProfiles(JSON.parse(saved))}catch{}},[])
 const accounts=useMemo(()=>rawAccounts.map(a=>profiles[a.id]?{...a,...profiles[a.id]}:a),[rawAccounts,profiles])
 const saveProfile=(id:string,p:AccountProfile)=>{const next={...profiles,[id]:p};setProfiles(next);localStorage.setItem('tradedeck-account-profiles',JSON.stringify(next));setEditingAccount(null)}
 const totals=useMemo(()=>accounts.reduce((a,x)=>({equity:a.equity+x.equity,pnl:a.pnl+x.todayPnl,floating:a.floating+x.floatingPnl}),{equity:0,pnl:0,floating:0}),[accounts])
 const pnlPct=totals.equity?totals.pnl/(totals.equity-totals.pnl)*100:0
 const title=tab==='dashboard'?'Portfolio':tab==='accounts'?'Accounts':tab==='risk'?'Risk Center':'Analytics'
 const funded=accounts.filter(a=>a.accountClass==='funded'); const challenge=accounts.filter(a=>a.accountClass==='challenge'); const personal=accounts.filter(a=>a.accountClass==='personal')
 return <main className="shell">
   <header><div><div className="eyebrow"><Activity size={14}/> TRADEDECK</div><h1>{title}</h1></div><button className="iconBtn" onClick={load} aria-label="Refresh"><RefreshCw size={18} className={loading?'spin':''}/></button></header>
   {tab==='dashboard'&&<>
    <section className="hero"><div className="heroTop"><span>TOTAL EQUITY</span><span className="live"><i/> LIVE</span></div><div className="big">{money(totals.equity)}</div><div className={totals.pnl>=0?'gain':'loss'}>{totals.pnl>=0?<ArrowUpRight size={17}/>:<ArrowDownRight size={17}/>} {money(Math.abs(totals.pnl))} today <small>{pnlPct>=0?'+':''}{pnlPct.toFixed(2)}%</small></div><div className="heroGrid"><div><span>Floating P&L</span><strong className={totals.floating>=0?'positive':'negative'}>{totals.floating>=0?'+':''}{money(totals.floating)}</strong></div><div><span>Accounts</span><strong>{accounts.length}</strong></div></div></section>
    {!!funded.length&&<><div className="sectionTitle"><span>REAL / FUNDED</span><button onClick={()=>setTab('accounts')}>View all</button></div><section className="list">{funded.slice(0,3).map(a=><AccountCard key={a.id} a={a}/>)}</section></>}
    {!!challenge.length&&<><div className="sectionTitle"><span>DEMO / CHALLENGE</span></div><section className="list">{challenge.slice(0,3).map(a=><AccountCard key={a.id} a={a}/>)}</section></>}
    {!!personal.length&&<><div className="sectionTitle"><span>PERSONAL</span></div><section className="list">{personal.slice(0,3).map(a=><AccountCard key={a.id} a={a}/>)}</section></>}
    <section className="insight" onClick={()=>setTab('risk')}><div className="insightIcon"><ShieldCheck/></div><div><b>Risk overview</b><p>Risk limits are configured manually per account.</p></div><ChevronRight/></section>
   </>}
   {tab==='accounts'&&<GroupedAccounts funded={funded} challenge={challenge} personal={personal} onEdit={setEditingAccount}/>} 
   {tab==='risk'&&<Risk accounts={accounts}/>} 
   {tab==='analytics'&&<Analytics accounts={accounts}/>} 
   <nav><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}><LayoutDashboard/><span>Home</span></button><button className={tab==='accounts'?'active':''} onClick={()=>setTab('accounts')}><WalletCards/><span>Accounts</span></button><button className={tab==='risk'?'active':''} onClick={()=>setTab('risk')}><ShieldCheck/><span>Risk</span></button><button className={tab==='analytics'?'active':''} onClick={()=>setTab('analytics')}><BarChart3/><span>Analytics</span></button></nav>
   {editingAccount&&<AccountModal account={editingAccount} onClose={()=>setEditingAccount(null)} onSave={saveProfile}/>} 
 </main>
}
function GroupedAccounts({funded,challenge,personal,onEdit}:{funded:TradeAccount[];challenge:TradeAccount[];personal:TradeAccount[];onEdit:(a:TradeAccount)=>void}){return <div className="accountsPage"><AccountGroup title="REAL / FUNDED" items={funded} onEdit={onEdit}/><AccountGroup title="DEMO / CHALLENGE" items={challenge} onEdit={onEdit} challenge/><AccountGroup title="PERSONAL" items={personal} onEdit={onEdit} personal/></div>}
function AccountGroup({title,items,onEdit,challenge=false,personal=false}:{title:string;items:TradeAccount[];onEdit:(a:TradeAccount)=>void;challenge?:boolean;personal?:boolean}){if(!items.length)return null;return <><div className={`groupHeader ${challenge?'challengeHead':''} ${personal?'personalHead':''}`}><span>{title}</span><b>{items.length}</b></div><section className="list">{items.map(a=><AccountCard key={a.id} a={a} detailed onEdit={()=>onEdit(a)}/>)}</section></>}
function AccountCard({a,detailed=false,onEdit}:{a:TradeAccount;detailed?:boolean;onEdit?:()=>void}){const used=a.drawdownLimit?Math.min(100,a.drawdownPct/a.drawdownLimit*100):0;return <article className="card"><div className="cardHead"><div><div className="accountName">{a.name}</div><div className="meta"><span className={`dot ${a.status}`}/>{a.platform} · {a.broker}</div><div className={`accountBadge ${a.accountClass}`}>{a.stageLabel}</div></div><div className="equity"><small>EQUITY</small><b>{money(a.equity)}</b>{detailed&&onEdit&&<button className="editAccountBtn" onClick={onEdit}><Edit3 size={13}/> Edit</button>}</div></div><div className="stats"><div><span>Today</span><b className={a.todayPnl>=0?'positive':'negative'}>{a.todayPnl>=0?'+':''}{money(a.todayPnl)}</b></div><div><span>Floating</span><b className={a.floatingPnl>=0?'positive':'negative'}>{a.floatingPnl>=0?'+':''}{money(a.floatingPnl)}</b></div><div><span>Drawdown</span><b>{a.drawdownPct.toFixed(1)}%</b></div></div><div className="progressLabel"><span>DD usage</span><span>{used.toFixed(0)}% of current demo limit</span></div><div className="bar"><i style={{width:`${used}%`}} className={used>70?'warn':''}/></div>{detailed&&a.targetPct>0&&<div className="target"><span>Challenge progress</span><strong>{a.progressPct}%</strong></div>}</article>}
function AccountModal({account,onClose,onSave}:{account:TradeAccount;onClose:()=>void;onSave:(id:string,p:AccountProfile)=>void}){const [name,setName]=useState(account.name);const [kind,setKind]=useState<AccountClass>(account.accountClass);const [stage,setStage]=useState(account.stageLabel);const submit=()=>onSave(account.id,{name:name.trim()||account.name,accountClass:kind,stageLabel:stage.trim()||defaultStage(kind)});return <div className="modalBackdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><span>ACCOUNT SETTINGS</span><b>{account.platform} · {account.broker}</b><small>TradeDeck display settings</small></div><button onClick={onClose}><X/></button></div><label>Display name<input value={name} onChange={e=>setName(e.target.value)} /></label><label>Account type<div className="typePicker"><button className={kind==='funded'?'selected':''} onClick={()=>{setKind('funded');setStage('Funded / Real')}}>Real / Funded</button><button className={kind==='challenge'?'selected':''} onClick={()=>{setKind('challenge');setStage('Phase 1')}}>Demo / Challenge</button><button className={kind==='personal'?'selected':''} onClick={()=>{setKind('personal');setStage('Personal')}}>Personal</button></div></label><label>Stage / label<input value={stage} onChange={e=>setStage(e.target.value)} placeholder="e.g. Instant, Phase 1, Funded"/></label><button className="saveBtn" onClick={submit}>Save account settings</button></div></div>}
const defaultStage=(kind:AccountClass)=>kind==='funded'?'Funded / Real':kind==='challenge'?'Challenge':'Personal'
function Risk({accounts}:{accounts:TradeAccount[]}){const [rules,setRules]=useState<RiskRules>({}); const [editing,setEditing]=useState<TradeAccount|null>(null);useEffect(()=>{try{const saved=localStorage.getItem('tradedeck-risk-rules');if(saved)setRules(JSON.parse(saved))}catch{}},[]);const save=(id:string,rule:RiskRule)=>{const next={...rules,[id]:rule};setRules(next);localStorage.setItem('tradedeck-risk-rules',JSON.stringify(next));setEditing(null)};const configured=accounts.filter(a=>rules[a.id]); const maxUsage=configured.reduce((m,a)=>Math.max(m,a.drawdownPct/(rules[a.id]?.maxLoss||100)*100),0);const label=!configured.length?'SETUP':maxUsage>=85?'HIGH':maxUsage>=60?'MEDIUM':'LOW';return <section className="riskPage"><div className="riskScore"><span>PORTFOLIO RISK</span><strong>{label}</strong><p>{!configured.length?'Add manual risk rules for each account.':label==='LOW'?'Configured accounts are within your manual limits.':'One or more accounts are approaching a configured limit.'}</p></div><h3>Account risk rules</h3>{accounts.map(a=>{const r=rules[a.id];const used=r?Math.min(100,a.drawdownPct/r.maxLoss*100):0;return <div className="riskRuleCard" key={a.id}><div className="riskRuleTop"><div><b>{a.name}</b><span>{a.stageLabel} · {a.platform}</span></div><button onClick={()=>setEditing(a)}><Plus size={15}/>{r?'Edit':'Risk Rule'}</button></div>{r?<><div className="ruleGrid"><div><span>Daily loss</span><b>{r.dailyLoss}%</b></div><div><span>Max loss</span><b>{r.maxLoss}%</b></div><div><span>Per trade</span><b>{r.perTrade}%</b></div></div><div className="progressLabel"><span>Current DD vs max</span><span>{a.drawdownPct.toFixed(1)}% / {r.maxLoss}%</span></div><div className="bar"><i style={{width:`${used}%`}} className={used>70?'warn':''}/></div></>:<div className="emptyRule">No rule set yet. Add this account's own prop or personal limits.</div>}</div>})}<div className="alertBox"><AlertTriangle/><div><b>Rules stay account-specific</b><p>Instant, phased, funded and personal accounts can all use different limits even when they are from the same firm.</p></div></div>{editing&&<RiskModal account={editing} initial={rules[editing.id]} onClose={()=>setEditing(null)} onSave={save}/>}</section>}
function RiskModal({account,initial,onClose,onSave}:{account:TradeAccount;initial?:RiskRule;onClose:()=>void;onSave:(id:string,r:RiskRule)=>void}){const [daily,setDaily]=useState(String(initial?.dailyLoss??5));const [max,setMax]=useState(String(initial?.maxLoss??10));const [trade,setTrade]=useState(String(initial?.perTrade??0.5));const submit=()=>onSave(account.id,{dailyLoss:Number(daily)||0,maxLoss:Number(max)||0,perTrade:Number(trade)||0});return <div className="modalBackdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><span>MANUAL RISK RULE</span><b>{account.name}</b><small>{account.stageLabel}</small></div><button onClick={onClose}><X/></button></div><label>Daily loss limit (%)<input inputMode="decimal" value={daily} onChange={e=>setDaily(e.target.value)}/></label><label>Maximum loss limit (%)<input inputMode="decimal" value={max} onChange={e=>setMax(e.target.value)}/></label><label>Personal risk per trade (%)<input inputMode="decimal" value={trade} onChange={e=>setTrade(e.target.value)}/></label><button className="saveBtn" onClick={submit}>Save risk rule</button></div></div>}
function Analytics({accounts}:{accounts:TradeAccount[]}){const totalPnl=accounts.reduce((s,a)=>s+a.todayPnl,0);const avgDd=accounts.length?accounts.reduce((s,a)=>s+(a.drawdownLimit?a.drawdownPct/a.drawdownLimit*100:0),0)/accounts.length:0;const best=[...accounts].sort((a,b)=>b.todayPct-a.todayPct)[0];const worst=[...accounts].sort((a,b)=>a.todayPct-b.todayPct)[0];const maxAbs=Math.max(1,...accounts.map(a=>Math.abs(a.todayPnl)));return <section className="analyticsPage"><div className="analyticsGrid"><div className="metric"><span>TODAY P&L</span><strong className={totalPnl>=0?'positive':'negative'}>{totalPnl>=0?'+':''}{money(totalPnl)}</strong><small>Combined portfolio</small></div><div className="metric"><span>AVG DD USAGE</span><strong>{avgDd.toFixed(0)}%</strong><small>Across all accounts</small></div></div><div className="analyticsSplit"><div><span>BEST TODAY</span><b>{best?.name||'—'}</b><strong className="positive">{best?`+${best.todayPct.toFixed(2)}%`:'—'}</strong></div><div><span>WORST TODAY</span><b>{worst?.name||'—'}</b><strong className={worst&&worst.todayPct<0?'negative':'positive'}>{worst?`${worst.todayPct>=0?'+':''}${worst.todayPct.toFixed(2)}%`:'—'}</strong></div></div><h3>Account performance</h3><div className="performanceList">{accounts.map(a=>{const width=Math.max(5,Math.abs(a.todayPnl)/maxAbs*100);return <div className="perfRow" key={a.id}><div><b>{a.name}</b><span>{a.stageLabel}</span></div><div className="perfTrack"><i className={a.todayPnl<0?'negativeBar':''} style={{width:`${width}%`}}/></div><strong className={a.todayPnl>=0?'positive':'negative'}>{a.todayPnl>=0?'+':''}{money(a.todayPnl)}</strong></div>})}</div><div className="analyticsNote"><BarChart3/><div><b>Trade history analytics comes next</b><p>Gerçek hesap bağlantısından sonra win rate, average R:R, profit factor, symbol breakdown ve günlük/haftalık performans grafikleri burada oluşacak.</p></div></div></section>}
