'use client'
import {useEffect,useMemo,useState} from 'react'
import {Activity,AlertTriangle,ArrowDownRight,ArrowUpRight,BarChart3,ChevronRight,LayoutDashboard,Plus,RefreshCw,ShieldCheck,WalletCards,X} from 'lucide-react'
import type {TradeAccount} from '@/lib/demo'

type Tab='dashboard'|'accounts'|'risk'|'analytics'
type RiskRule={dailyLoss:number;maxLoss:number;perTrade:number}
type RiskRules=Record<string,RiskRule>
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)

export default function Home(){
 const [accounts,setAccounts]=useState<TradeAccount[]>([]); const [tab,setTab]=useState<Tab>('dashboard'); const [loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/accounts',{cache:'no-store'});const j=await r.json();setAccounts(j.accounts||[])}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const totals=useMemo(()=>accounts.reduce((a,x)=>({equity:a.equity+x.equity,pnl:a.pnl+x.todayPnl,floating:a.floating+x.floatingPnl}),{equity:0,pnl:0,floating:0}),[accounts])
 const pnlPct=totals.equity?totals.pnl/(totals.equity-totals.pnl)*100:0
 const title=tab==='dashboard'?'Portfolio':tab==='accounts'?'Accounts':tab==='risk'?'Risk Center':'Analytics'
 const real=accounts.filter(a=>a.accountClass==='real'); const challenge=accounts.filter(a=>a.accountClass==='challenge')
 return <main className="shell">
   <header><div><div className="eyebrow"><Activity size={14}/> TRADEDECK</div><h1>{title}</h1></div><button className="iconBtn" onClick={load} aria-label="Refresh"><RefreshCw size={18} className={loading?'spin':''}/></button></header>
   {tab==='dashboard'&&<>
    <section className="hero"><div className="heroTop"><span>TOTAL EQUITY</span><span className="live"><i/> LIVE</span></div><div className="big">{money(totals.equity)}</div><div className={totals.pnl>=0?'gain':'loss'}>{totals.pnl>=0?<ArrowUpRight size={17}/>:<ArrowDownRight size={17}/>} {money(Math.abs(totals.pnl))} today <small>{pnlPct>=0?'+':''}{pnlPct.toFixed(2)}%</small></div><div className="heroGrid"><div><span>Floating P&L</span><strong className={totals.floating>=0?'positive':'negative'}>{totals.floating>=0?'+':''}{money(totals.floating)}</strong></div><div><span>Accounts</span><strong>{accounts.length}</strong></div></div></section>
    <div className="sectionTitle"><span>REAL / FUNDED</span><button onClick={()=>setTab('accounts')}>View all</button></div><section className="list">{real.slice(0,3).map(a=><AccountCard key={a.id} a={a}/>)}</section>
    {!!challenge.length&&<><div className="sectionTitle"><span>DEMO / CHALLENGE</span></div><section className="list">{challenge.slice(0,3).map(a=><AccountCard key={a.id} a={a}/>)}</section></>}
    <section className="insight" onClick={()=>setTab('risk')}><div className="insightIcon"><ShieldCheck/></div><div><b>Risk overview</b><p>Risk limits are configured manually per account.</p></div><ChevronRight/></section>
   </>}
   {tab==='accounts'&&<GroupedAccounts real={real} challenge={challenge}/>} 
   {tab==='risk'&&<Risk accounts={accounts}/>} 
   {tab==='analytics'&&<Analytics accounts={accounts}/>} 
   <nav><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}><LayoutDashboard/><span>Home</span></button><button className={tab==='accounts'?'active':''} onClick={()=>setTab('accounts')}><WalletCards/><span>Accounts</span></button><button className={tab==='risk'?'active':''} onClick={()=>setTab('risk')}><ShieldCheck/><span>Risk</span></button><button className={tab==='analytics'?'active':''} onClick={()=>setTab('analytics')}><BarChart3/><span>Analytics</span></button></nav>
 </main>
}
function GroupedAccounts({real,challenge}:{real:TradeAccount[];challenge:TradeAccount[]}){return <div className="accountsPage"><div className="groupHeader"><span>REAL / FUNDED</span><b>{real.length}</b></div><section className="list">{real.map(a=><AccountCard key={a.id} a={a} detailed/>)}</section><div className="groupHeader challengeHead"><span>DEMO / CHALLENGE</span><b>{challenge.length}</b></div><section className="list">{challenge.map(a=><AccountCard key={a.id} a={a} detailed/>)}</section></div>}
function AccountCard({a,detailed=false}:{a:TradeAccount;detailed?:boolean}){const used=a.drawdownLimit?Math.min(100,a.drawdownPct/a.drawdownLimit*100):0;return <article className="card"><div className="cardHead"><div><div className="accountName">{a.name}</div><div className="meta"><span className={`dot ${a.status}`}/>{a.platform} · {a.broker}</div><div className={`accountBadge ${a.accountClass}`}>{a.stageLabel}</div></div><div className="equity"><small>EQUITY</small><b>{money(a.equity)}</b></div></div><div className="stats"><div><span>Today</span><b className={a.todayPnl>=0?'positive':'negative'}>{a.todayPnl>=0?'+':''}{money(a.todayPnl)}</b></div><div><span>Floating</span><b className={a.floatingPnl>=0?'positive':'negative'}>{a.floatingPnl>=0?'+':''}{money(a.floatingPnl)}</b></div><div><span>Drawdown</span><b>{a.drawdownPct.toFixed(1)}%</b></div></div><div className="progressLabel"><span>DD usage</span><span>{used.toFixed(0)}% of current demo limit</span></div><div className="bar"><i style={{width:`${used}%`}} className={used>70?'warn':''}/></div>{detailed&&a.targetPct>0&&<div className="target"><span>Challenge progress</span><strong>{a.progressPct}%</strong></div>}</article>}
function Risk({accounts}:{accounts:TradeAccount[]}){
 const [rules,setRules]=useState<RiskRules>({}); const [editing,setEditing]=useState<TradeAccount|null>(null)
 useEffect(()=>{try{const saved=localStorage.getItem('tradedeck-risk-rules');if(saved)setRules(JSON.parse(saved))}catch{}},[])
 const save=(id:string,rule:RiskRule)=>{const next={...rules,[id]:rule};setRules(next);localStorage.setItem('tradedeck-risk-rules',JSON.stringify(next));setEditing(null)}
 const configured=accounts.filter(a=>rules[a.id]); const maxUsage=configured.reduce((m,a)=>Math.max(m,a.drawdownPct/(rules[a.id]?.maxLoss||100)*100),0);const label=!configured.length?'SETUP':maxUsage>=85?'HIGH':maxUsage>=60?'MEDIUM':'LOW'
 return <section className="riskPage"><div className="riskScore"><span>PORTFOLIO RISK</span><strong>{label}</strong><p>{!configured.length?'Add manual risk rules for each account.':label==='LOW'?'Configured accounts are within your manual limits.':'One or more accounts are approaching a configured limit.'}</p></div><h3>Account risk rules</h3>{accounts.map(a=>{const r=rules[a.id];const used=r?Math.min(100,a.drawdownPct/r.maxLoss*100):0;return <div className="riskRuleCard" key={a.id}><div className="riskRuleTop"><div><b>{a.name}</b><span>{a.stageLabel} · {a.platform}</span></div><button onClick={()=>setEditing(a)}><Plus size={15}/>{r?'Edit':'Risk Rule'}</button></div>{r?<><div className="ruleGrid"><div><span>Daily loss</span><b>{r.dailyLoss}%</b></div><div><span>Max loss</span><b>{r.maxLoss}%</b></div><div><span>Per trade</span><b>{r.perTrade}%</b></div></div><div className="progressLabel"><span>Current DD vs max</span><span>{a.drawdownPct.toFixed(1)}% / {r.maxLoss}%</span></div><div className="bar"><i style={{width:`${used}%`}} className={used>70?'warn':''}/></div></>:<div className="emptyRule">No rule set yet. Add this account's own prop or personal limits.</div>}</div>})}<div className="alertBox"><AlertTriangle/><div><b>Rules stay account-specific</b><p>Instant, phased, funded and personal accounts can all use different limits even when they are from the same firm.</p></div></div>{editing&&<RiskModal account={editing} initial={rules[editing.id]} onClose={()=>setEditing(null)} onSave={save}/>}</section>
}
function RiskModal({account,initial,onClose,onSave}:{account:TradeAccount;initial?:RiskRule;onClose:()=>void;onSave:(id:string,r:RiskRule)=>void}){const [daily,setDaily]=useState(String(initial?.dailyLoss??5));const [max,setMax]=useState(String(initial?.maxLoss??10));const [trade,setTrade]=useState(String(initial?.perTrade??0.5));const submit=()=>onSave(account.id,{dailyLoss:Number(daily)||0,maxLoss:Number(max)||0,perTrade:Number(trade)||0});return <div className="modalBackdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><span>MANUAL RISK RULE</span><b>{account.name}</b><small>{account.stageLabel}</small></div><button onClick={onClose}><X/></button></div><label>Daily loss limit (%)<input inputMode="decimal" value={daily} onChange={e=>setDaily(e.target.value)}/></label><label>Maximum loss limit (%)<input inputMode="decimal" value={max} onChange={e=>setMax(e.target.value)}/></label><label>Personal risk per trade (%)<input inputMode="decimal" value={trade} onChange={e=>setTrade(e.target.value)}/></label><button className="saveBtn" onClick={submit}>Save risk rule</button></div></div>}
function Analytics({accounts}:{accounts:TradeAccount[]}){
 const totalPnl=accounts.reduce((s,a)=>s+a.todayPnl,0)
 const avgDd=accounts.length?accounts.reduce((s,a)=>s+(a.drawdownLimit?a.drawdownPct/a.drawdownLimit*100:0),0)/accounts.length:0
 const best=[...accounts].sort((a,b)=>b.todayPct-a.todayPct)[0]
 const worst=[...accounts].sort((a,b)=>a.todayPct-b.todayPct)[0]
 const maxAbs=Math.max(1,...accounts.map(a=>Math.abs(a.todayPnl)))
 return <section className="analyticsPage"><div className="analyticsGrid"><div className="metric"><span>TODAY P&L</span><strong className={totalPnl>=0?'positive':'negative'}>{totalPnl>=0?'+':''}{money(totalPnl)}</strong><small>Combined portfolio</small></div><div className="metric"><span>AVG DD USAGE</span><strong>{avgDd.toFixed(0)}%</strong><small>Across all accounts</small></div></div><div className="analyticsSplit"><div><span>BEST TODAY</span><b>{best?.name||'—'}</b><strong className="positive">{best?`+${best.todayPct.toFixed(2)}%`:'—'}</strong></div><div><span>WORST TODAY</span><b>{worst?.name||'—'}</b><strong className={worst&&worst.todayPct<0?'negative':'positive'}>{worst?`${worst.todayPct>=0?'+':''}${worst.todayPct.toFixed(2)}%`:'—'}</strong></div></div><h3>Account performance</h3><div className="performanceList">{accounts.map(a=>{const width=Math.max(5,Math.abs(a.todayPnl)/maxAbs*100);return <div className="perfRow" key={a.id}><div><b>{a.name}</b><span>{a.stageLabel}</span></div><div className="perfTrack"><i className={a.todayPnl<0?'negativeBar':''} style={{width:`${width}%`}}/></div><strong className={a.todayPnl>=0?'positive':'negative'}>{a.todayPnl>=0?'+':''}{money(a.todayPnl)}</strong></div>})}</div><div className="analyticsNote"><BarChart3/><div><b>Trade history analytics comes next</b><p>Gerçek hesap bağlantısından sonra win rate, average R:R, profit factor, symbol breakdown ve günlük/haftalık performans grafikleri burada oluşacak.</p></div></div></section>
}
